export const TYPE_RECOIL = {
  SEARCH_LIST: 'SEARCH_LIST',
  GET_SEARCH_LIST: 'GET_SEARCH_LIST',
  TODO_LIST: 'TODO_LIST',
  ADD_TODO: 'ADD_TODO',
  UPDATE_CHECKED_TODO: 'UPDATE_CHECKED_TODO',
  DELETE_TODO: 'DELETE_TODO',
};
